name: Production Tag Deployment
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "*" # Push events to every tag not containing /
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: |
          export RELEASE_NOTES=$(gh release view $TAG --json body | jq .body)
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ env.RELEASE_VERSION }}
      - name: Send to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C05NW7MFUCC" # news channel
          slack-message: "🌟 New release: ${{ env.RELEASE_VERSION }}\nWe have released a new version of CRBN AI. You can find the release notes here: https://github.com/AI-Skunkworks/crbn-ai/releases/tag/${{ env.RELEASE_VERSION }}\n\nRelease Notes:\n$RELEASE_NOTES"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
