name: Try
on:
  push:
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          export RELEASE_NOTES=$(gh release view $TAG --json body -q .body)
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
          TAG: 0.1.0
      - name: Test
        run: echo $RELEASE_NOTES
