name: Try
on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          export RELEASE_NOTES=$(gh release view $TAG --json body | jq .body)
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
          TAG: 0.5.0
      - name: Test
        run: echo $RELEASE_NOTES

      - name: Send to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C05NW7MFUCC" # news channel
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🌟 New release: ${{ env.RELEASE_VERSION }}\nWe have released a new version of CRBN AI. You can find the release notes here: https://github.com/AI-Skunkworks/crbn-ai/releases/tag/${{ env.RELEASE_VERSION }}\n\nRelease Notes:\n${{ env.RELEASE_NOTES }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
