name: Try
on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          export RELEASE_NOTES=$(gh release view $TAG --json body | jq .body)
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
          TAG: 0.5.0
      - name: Test
        run: echo $RELEASE_NOTES

      - name: Send to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "C05NW7MFUCC" # news channel
          payload-file-path: .github/workflows/payload.json
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
